[book]
title = "ZERO Documentation"
authors = ["The Neuro-Catalyst Group"]
description = "ZERO Documentation"
language = "en"
text-direction = "ltr"
src = "docs"

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true       # use the default preprocessors
extra-watch-dirs = []                  # directories to watch for triggering builds

[preprocessor.index]

[preprocessor.links]

[output.html]
# additional-css = ["custom.css"]
# theme = "my-theme"
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
definition-lists = true
admonitions = true
mathjax-support = false
# additional-js = ["custom.js"]
no-section-label = false
git-repository-url = "https://github.com/rust-lang/mdBook"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"
site-url = "/example-book/"
cname = "myproject.rs"
input-404 = "not-found.md"
sidebar-header-nav = true

[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true           # include Javascript code for search
