#!/bin/bash
set -e

echo "🔧 ZERO CI/CD Repair Script"
echo "=============================="

# 1. Create missing configuration files
echo "📝 Creating configuration files..."

# Create .commitlintrc.json
cat > .commitlintrc.json << 'EOF'
{
  "extends": ["@commitlint/config-conventional"],
  "rules": {
    "type-enum": [
      2,
      "always",
      ["feat", "fix", "docs", "style", "refactor", "perf", "test", "chore", "ci", "security"]
    ],
    "subject-case": [2, "never", ["start-case", "pascal-case", "upper-case"]],
    "scope-case": [2, "always", "lower-case"]
  }
}
EOF

# 2. Create docker directory for Dockerfiles
echo "📦 Creating Docker configuration..."
mkdir -p docker

for service in cli tui ui server; do
  cat > docker/Dockerfile.$service << EOF
FROM rust:1.85-slim as builder
WORKDIR /app
COPY . .
RUN cargo build --release -p $service

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/$service /usr/local/bin/
ENV APP_VERSION=\${VERSION:-0.1.0}
ENTRYPOINT ["$service"]
EOF
done

# 3. Create test configuration
echo "🧪 Creating test configuration..."
mkdir -p tests/postman
mkdir -p tests/environments

cat > tests/postman/smoke-tests.json << 'EOF'
{
  "info": {
    "name": "Smoke Tests",
    "description": "Basic API smoke tests"
  },
  "item": [
    {
      "name": "Health Check",
      "request": {
        "method": "GET",
        "url": "{{base_url}}/health"
      }
    }
  ]
}
EOF

cat > tests/environments/production.json << 'EOF'
{
  "name": "Production",
  "values": [
    {
      "key": "base_url",
      "value": "https://zero.app"
    }
  ]
}
EOF

cat > tests/environments/staging.json << 'EOF'
{
  "name": "Staging",
  "values": [
    {
      "key": "base_url",
      "value": "https://staging.zero.app"
    }
  ]
}
EOF

# 4. Create GitHub secrets configuration template
echo "🔐 Creating secrets template..."
cat > .github/SECRETS_TEMPLATE.md << 'EOF'
# GitHub Secrets Configuration

Add these secrets to your GitHub repository:

## Deployment
- `GITHUB_TOKEN` - Auto-generated by GitHub

## Docker Registry
- `DOCKER_USERNAME` - Docker Hub username
- `DOCKER_PASSWORD` - Docker Hub token

## Code Signing
- `APPLE_DEVELOPER_ID` - Apple Developer ID (optional)
- `APPLE_SIGNING_KEY` - Apple signing certificate (optional)
- `WINDOWS_SIGNING_KEY` - Windows code signing cert (optional)

## Publishing
- `CARGO_REGISTRY_TOKEN` - crates.io token
- `NPM_TOKEN` - npm registry token

## Notifications
- `SLACK_CI_WEBHOOK` - Slack webhook for CI
- `SLACK_DEPLOYMENTS_WEBHOOK` - Slack webhook for deployments
- `SLACK_ALERTS_WEBHOOK` - Slack webhook for alerts
- `SLACK_RELEASE_WEBHOOK` - Slack webhook for releases
- `SLACK_SECURITY_WEBHOOK` - Slack webhook for security

## Cloud/Services (if used)
- `DATADOG_API_KEY` - DataDog integration (optional)
- `SENTRY_DSN` - Sentry error tracking (optional)
EOF

# 5. Fix workflow trigger paths
echo "⚙️ Validating workflows..."
for workflow in .github/workflows/*.yml; do
  if grep -q "paths:" "$workflow"; then
    echo "✓ $(basename $workflow) has path triggers"
  fi
done

# 6. Create PR/Issue templates if missing
echo "📋 Creating PR/Issue templates..."
mkdir -p .github/ISSUE_TEMPLATE

cat > .github/ISSUE_TEMPLATE/bug_report.md << 'EOF'
---
name: Bug Report
about: Report a bug
title: "[BUG] "
labels: bug
---

**Description**
<!-- Clear description of the bug -->

**Steps to Reproduce**
1. 
2. 
3. 

**Expected vs Actual**
- Expected: 
- Actual: 

**Environment**
- OS: 
- Version: 
EOF

cat > .github/ISSUE_TEMPLATE/feature_request.md << 'EOF'
---
name: Feature Request
about: Suggest an enhancement
title: "[FEATURE] "
labels: enhancement
---

**Description**
<!-- Clear description of feature -->

**Use Case**
<!-- Why is this needed -->

**Proposed Solution**
<!-- How should this work -->
EOF

# 7. Validate test setup script
echo "🧪 Validating test setup..."
if [ ! -f "scripts/setup_test_data.sh" ]; then
  echo "❌ scripts/setup_test_data.sh not found!"
  exit 1
fi

# Make it executable
chmod +x scripts/*.sh

# 8. Create workflow action inputs validation
echo "✅ Creating workflow validation..."
cat > .github/workflows/_validate-secrets.yml << 'EOF'
name: Validate Secrets

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check critical secrets
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "❌ GITHUB_TOKEN is missing"
            exit 1
          fi
          echo "✅ All critical secrets are set"
EOF

# 9. Generate .gitignore additions
echo "🚫 Creating .gitignore rules..."
cat >> .gitignore << 'EOF'

# GitHub Actions
.github/workflows/logs/
.act/

# Test artifacts
test_data/
playwright-report/
coverage/

# Build artifacts
dist/
build/

# IDE
.vscode/
.idea/
EOF

# 10. Create workflow documentation
echo "📚 Creating workflow documentation..."
cat > .github/WORKFLOWS.md << 'EOF'
# ZERO CI/CD Workflows

## Triggers

### On Push to Main
- **CI Pipeline** - Lint, test, build
- **Security Audit** - Vulnerability scan
- **CodeQL** - Code analysis

### On Pull Request
- **CI Pipeline** - All checks required
- **Dependency Review** - Check dependencies

### On Release Tag (v*)
- **Release Pipeline** - Build & publish
- **Deployment** - Deploy to staging/production

### On Extension Tag (ext-*)
- **Gemini Extension Release** - Build & publish extension

### Scheduled
- **Security Audit** - Daily at 2 AM UTC
- **Maintenance** - Weekly dependency updates
- **Health Checks** - Every 30 minutes

## Required Secrets

See `.github/SECRETS_TEMPLATE.md`

## Debugging Workflows

To debug locally:
```bash
brew install act
act -l                    # List all workflows
act push                  # Simulate push event
act -j test-job          # Run specific job