[package]
name = "ingestor"
description = "Universal Data Ingestor for ZERO"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
clap.workspace = true
thiserror.workspace = true
bytes.workspace = true
tokio.workspace = true
rusqlite = { version = "0.38.0", features = ["bundled"] }
serde_json.workspace = true
mongodb.workspace = true
serde.workspace = true
neo4rs.workspace = true
url.workspace = true
tokio-postgres.workspace = true
tokio-postgres-rustls.workspace = true
rustls.workspace = true
deadpool-postgres.workspace = true
qdrant-client.workspace = true
uuid.workspace = true
dotenvy.workspace = true
reqwest.workspace = true
backoff.workspace = true
walkdir.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
anyhow.workspace = true
schema = { path = "../schema" }
config = { path = "../config" }
reader = { path = "../reader", features = ["base-formats"] }

[dev-dependencies]
tempfile.workspace = true
